// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoundApi.Data;

#nullable disable

namespace SoundApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoundApi.Models.Sound", b =>
                {
                    b.Property<int>("SoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sound_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SoundId"));

                    b.Property<DateTime>("SoundCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sound_created_datetime");

                    b.Property<byte[]>("SoundData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sound_data");

                    b.Property<string>("SoundExtension")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("sound_extension");

                    b.Property<string>("SoundName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sound_name");

                    b.Property<DateTime?>("SoundUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sound_updated_datetime");

                    b.HasKey("SoundId");

                    b.ToTable("Sounds");
                });
#pragma warning restore 612, 618
        }
    }
}
