// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Contract
{

public enum MessageType : byte
{
  NONE = 0,
  SelectAllSound = 1,
  SelectSoundIds = 2,
  CreateSound = 3,
  ModifySound = 4,
  DeleteSound = 5,
  Sound = 6,
};


}
